### ISSUE TITLE
Deluge 2.0 TorrentsStatus error

### ISSUE THREAD

**Issue by l3uddz** [gdm85/go-libdeluge#19]
Hi,

Nice package.

I have an issue however trying to work with a V2 daemon.

The following error is being returned for the `TorrentsStatus` method:

`strconv.Atoi: parsing "1E04.Facing.the.Hangman.1080p.NF.WEB-DL.DDP5.1.x264-NTG.mkv\x84sizeA\x00\x00\x00\x00\x9d\xa93\x0e\x86offsetA\x00\x00\x00\x01ƾ\xc9 j\x85index\x04\x84path134": invalid syntax`

This only appears to happen when `DebugSaveInteractions` is false, if its true it works as expected.

**Comment by gdm85** [comment]
It might be due to a timing bug on Deluge server side, I discussed this possibility briefly here: https://github.com/deluge-torrent/deluge/pull/224#issuecomment-558381470

Please use the `master` version of `go-libdeluge` (commit b5d327bcaf48a24e990464269db83a81f0fb0c06), enable `DebugSaveInteractions` and store the source data for the `TorrentStatus` call like in https://github.com/gdm85/go-libdeluge/blob/master/cli/cli.go#L164 but without the decompression (the original bytes from `buf.Bytes()` are needed); you can upload the tiny file directly here in a comment in a `.zip` file (it's an allowed extension).

**Comment by l3uddz** [comment]
> It might be due to a timing bug on Deluge server side, I discussed this possibility briefly here: [deluge-torrent/deluge#224 (comment)](https://github.com/deluge-torrent/deluge/pull/224#issuecomment-558381470)
> 
> Please use the `master` version of `go-libdeluge` (commit [b5d327b](https://github.com/gdm85/go-libdeluge/commit/b5d327bcaf48a24e990464269db83a81f0fb0c06)), enable `DebugSaveInteractions` and store the source data for the `TorrentStatus` call like in https://github.com/gdm85/go-libdeluge/blob/master/cli/cli.go#L164 but without the decompression (the original bytes from `buf.Bytes()` are needed); you can upload the tiny file directly here in a comment in a `.zip` file (it's an allowed extension).

I can do this later today.

Can I email you it instead as would rather not post potentially private data.

**Comment by gdm85** [comment]
@l3uddz I believe the issue is now fixed, please verify.

**Comment by l3uddz** [comment]
@gdm85 thanks i can confirm its now working.

however, the Label torrentstatus property appears to have been removed?

was this on purpose? 

this was a very useful parameter to have.

**Comment by l3uddz** [comment]
@gdm85 would it be possible to have the Label property back? 

i assume there was some issue with the SetLabel function which is why it was removed?

**Comment by gdm85** [comment]
@l3uddz you can open a new issue to discuss that
