### ISSUE TITLE
Feature: Label included in the TorrentStatus struct 

### ISSUE THREAD

**Issue by l3uddz** [gdm85/go-libdeluge#22]
Hi,

Would it be possible for the torrents label to be included in the returned TorrentStatus struct?

This piece of information is vital for any applications that may be using your package to discover torrents that meet certain criteria’s.

The property was there previously, however has since been removed.

Thanks

**Comment by gdm85** [comment]
> The property was there previously, however has since been removed.

It was introduced in https://github.com/gdm85/go-libdeluge/pull/7 and removed in 997d36670626505919afb8a033a6c0c4cdddf0bd because if the server has the plugin disabled it does not allow to fetch any torrent status.

Restoring the functionality as it was implemented is not an option; I am working on an implementation that allows to use plugins explicitly and only if possible.

**Comment by l3uddz** [comment]
I see, makes sense and good to hear theres an implementation being worked on.

I assume it will involve validating these capabilities are available (via exposed methods), perhaps on connect?

**Comment by gdm85** [comment]
I have implemented this in latest tagged `v0.4.1` and added an explanation in the README.
