### ISSUE TITLE
Save Path not working w/ Deluge v1

### ISSUE THREAD

**Issue by KyleSanderson** [gdm85/go-libdeluge#44]
hi there - thank you for this library 😺.

We're using options.DownloadLocation to set the save path, however a multitude of users (mostly on Discord) have reported this doesn't actually set the path for them with Deluge v1 (works w/ v2). Are you seeing the same thing?

Here's where we run the client: 
https://github.com/autobrr/autobrr/blob/ca196f0bf1a83d4ec5edc1006c982ca0fcaa7490/internal/action/deluge.go#L89

and the variable set:
https://github.com/autobrr/autobrr/blob/ca196f0bf1a83d4ec5edc1006c982ca0fcaa7490/internal/action/deluge.go#L316

Here's the user report: https://github.com/autobrr/autobrr/issues/727

**Comment by zze0s** [comment]
Another autobrr maintainer here.

I debugged the whole flow and removed [this else if check](https://github.com/gdm85/go-libdeluge/blob/1c98ff5abda9bcfa999be4a80a9c066ee85ee4e3/options.go#L77-L79) which sets `download_location` to `save_path` for v1 clients, specifically tested on `1.3.15`. 

With that block removed it does set the save path as expected.

Looking at the source, using the GitHub mirror since it has better search i found [this block of code](https://github.com/deluge-torrent/deluge/blob/366cded7be7fbc6a052502b1f4174935f53dc971/deluge/core/torrent.py#L549-L552) for the `1.3.15` tag.

```python
    @deprecated
    def set_save_path(self, download_location):
        """Deprecated: Use set_download_location."""
        self.set_download_location(download_location)
```

But it seems that does not get set properly in that version. I did not dig further.

I assume it might work in versions before `1.3.15` but I hope no one is running those.

## Suggested fix

My suggestion to fix this is to remove the else if mentioned earlier, since we can't set `name` as both `save_path` and `download_location`.

```diff
if !v2daemon {
	// map some v1 fields to the corresponding v2 field
	if name == "pre_allocate_storage" {
		name = "compact_allocation"
-	} else if name == "download_location" {
-		name = "save_path"
-               
	}
}
```

Removing it might break older versions than `1.3.15`, but again, I do not know anyone running those.

Maybe you have other ideas to support both @gdm85

**Comment by gdm85** [comment]
> i found [this block of code](https://github.com/deluge-torrent/deluge/blob/366cded7be7fbc6a052502b1f4174935f53dc971/deluge/core/torrent.py#L549-L552) for the `1.3.15` tag.

This is not 1.3.15 code, it is there since the 2.0.0 tag and missing in 1.3.x versions specifically.

> Removing it might break older versions than `1.3.15`, but again, I do not know anyone running those.

There is an integration test running against `1.3.15` however the download location functionality is not tested, only reading responses and sending requests.

The situation is the following:
1. deluge v1 does not send back `download_location` in responses, and does not read it when specified in options
2. deluge v2 supports both

So the fix proposed here would break it for deluge v1, since that version would not "see" the save_path/download_location anymore.

> With that block removed it does set the save path as expected.

I find this puzzling :thinking: but I will try to add an integration test to verify this functionality; after that a fix can be easily made.

**Comment by gdm85** [comment]
It should be fixed now; I will tag a new release.

Please comment if it's not fixed; I saw you made a fork, contributions are welcome if you have anything useful.

**Comment by zze0s** [comment]
> It should be fixed now; I will tag a new release.
> 
> Please comment if it's not fixed; I saw you made a fork, contributions are welcome if you have anything useful.

Thank you for fixing it! We did indeed fork it mainly to be able to pass context everywhere for cancellation and to quickly fix some types but it did introduce some errors that you have fixed now.

If you are not opposed to adding ctx to all methods I can PR that. It would be a breaking change for existing users so a major version bump would be needed, unless we duplicate all exported methods. It's up to you :smile:
